### PR TITLE
Remove check source when empty before publishing check result

### LINKED ISSUE #1836: Empty check source after token substitution
Addresses https://github.com/sensu/uchiwa/issues/762

Add a conditional to the sensu-client result publisher to remove check[:source] if empty, allowing the failed token substitution event to be under the sensu-client's scope/context instead of a client named `""`.

## Expected Behavior

The failed token substitution event is associated with the sensu-client (not the check source).

## Current Behavior

https://github.com/sensu/uchiwa/issues/762

## Possible Solution

Add a conditional to the sensu-client result publisher to remove check[:source] if empty, allowing the failed token substitution event to be under the sensu-client's scope/context instead of a client named `""`

## Steps to Reproduce (for bugs)

https://github.com/sensu/uchiwa/issues/762

## Context

https://github.com/sensu/uchiwa/issues/762

### PR DESCRIPTION
**Pull request by amdprophet**
Fixes #1836

Co-authored-by: Justin Kolberg <amd.prophet@gmail.com>
Co-authored-by: Aaron F. Stanton <afstanton@gmail.com>

## Related Issue
#1836

### CODE REVIEW

**Comment by amdprophet** [comment]
I bundled in the removal of `has_rdoc` which was causing a deprecation notice in mutator output causing a test to fail.

File: lib/sensu/client/process.rb [hunk 1]
```diff
@@ -84,6 +84,7 @@ def setup_keepalives
       #
       # @param check [Hash]
       def publish_check_result(check)
+        check.delete(:source) if check[:source] == ""
```
Comment (majormoses) [inline lib/sensu/client/process.rb]: any reason for `== ""`  `.empty?` just curious.

**Comment by portertech** [comment]
dog-dog
