### PR TITLE
Suppress stale check events when client keepalive event exists

### LINKED ISSUE #1282: Option to suppress expired TTL events when keepalive is failing
Currently when a check hasn't been run within the configured `TTL`, an event is generated with output: `Last check execution was X seconds ago`.

When a node is shut down, or otherwise disconnected from Sensu, a check result is generated for each check that hasn't been run within the `TTL`.

This information isn't really useful when the `keepalive` check failing is the real issue, so it would be helpful to be able to suppress expired `TTL` events when the `keepalive` check is failing.

### PR DESCRIPTION
**Pull request by cwjohnston**
## Description

Inspired by #1282, this pull request includes changes to suppress stale check events (i.e. checks with an expired ttl) when the relevant client has an active keepalive event.

Also updates spec config.json and API query helper to use `127.0.0.1` instead of `localhost` to help those of us with working IPv6 stacks :)

## Related Issue

Closes #1282

## Motivation and Context

Motivated by a desire to reduce the noise and boost the signal :)

#1282 and https://github.com/sensu/sensu/issues/861#issuecomment-130136052 describe the desire to suppress stale check events if keepalive is also alerting.

## How Has This Been Tested?

Added unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/sensu/server/process.rb [hunk 1]
```diff
@@ -619,6 +619,16 @@ def retrieve_client(result)
         end
       end
 
+      # Determine if a keepalive incident exists in the event registry.
+      #
+      # @param client_name [String] name of client to look up in event registry.
+      # @return [TrueClass, FalseClass]
+      def keepalive_event_exists?(client_name)
+        @redis.hexists("event:#{client_name}", "keepalive") do |event_exists|
```
Comment (portertech) [inline lib/sensu/server/process.rb]: should be "events:"

**Comment by portertech** [comment]
Going to merge and make a few minor changes, i.e. white space and language (incidents).
