### PR TITLE
[server/handle] use pipe handler status to set log level

### LINKED ISSUE #1542: Exception in Sensu handler is logged as info instead of error
When a Sensu handler raises an exception, its stack trace is logged with log level info instead of error, thus effectively hiding the stack trace when log output is restricted to warning or higher.

## Expected Behavior
    {"timestamp":"2017-01-20T12:44:34.229189+0100","level":"error","message":"handler failed","handler":{"type":"pipe","command":"P:/sensu/sensu/embedded/bin/ruby.exe P:/sensu/sensu/embedded/bin/handler-slack.rb","severites":["critical","unknown","warning"],"filters":["occurrences"],"name":"default"},"output":["P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval': (erubis:8: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\\n' (SyntaxError)\r\n\t\t\twhen 2: \"red\"\r\n\t\t\t       ^\r\n(erubis:9: syntax error, unexpected keyword_when, expecting ')'\r\n\t\t\twhen 1: \"yellow\"\r\n\t\t\t    ^\r\n(erubis:10: syntax error, unexpected keyword_when, expecting ')'\r\n\t\t\twhen 0: \"green\"\r\n\t\t\t    ^\r\n(erubis:11: syntax error, unexpected keyword_else, expecting ')'\r\n\t\t\telse: \"purple\"\r\n\t\t\t    ^\r\n(erubis:12: syntax error, unexpected keyword_end, expecting ')'\r\n(erubis:19: syntax error, unexpected end-of-input, expecting ')'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:102:in `render_payload_template'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:94:in `handle'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.4.2/lib/sensu-handler.rb:81:in `block in <class:Handler>'\r\n"]}

## Current Behavior
    {"timestamp":"2017-01-20T12:44:34.229189+0100","level":"info","message":"handler output","handler":{"type":"pipe","command":"P:/sensu/sensu/embedded/bin/ruby.exe P:/sensu/sensu/embedded/bin/handler-slack.rb","severites":["critical","unknown","warning"],"filters":["occurrences"],"name":"default"},"output":["P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval': (erubis:8: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\\n' (SyntaxError)\r\n\t\t\twhen 2: \"red\"\r\n\t\t\t       ^\r\n(erubis:9: syntax error, unexpected keyword_when, expecting ')'\r\n\t\t\twhen 1: \"yellow\"\r\n\t\t\t    ^\r\n(erubis:10: syntax error, unexpected keyword_when, expecting ')'\r\n\t\t\twhen 0: \"green\"\r\n\t\t\t    ^\r\n(erubis:11: syntax error, unexpected keyword_else, expecting ')'\r\n\t\t\telse: \"purple\"\r\n\t\t\t    ^\r\n(erubis:12: syntax error, unexpected keyword_end, expecting ')'\r\n(erubis:19: syntax error, unexpected end-of-input, expecting ')'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `result'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:102:in `render_payload_template'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugins-slack-1.0.0/bin/handler-slack.rb:94:in `handle'\r\n\tfrom P:/sensu/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.4.2/lib/sensu-handler.rb:81:in `block in <class:Handler>'\r\n"]}

## Possible Solution
Catch any exceptions raised by handlers and log an error to the sensu server log, including the stack trace.

## Steps to Reproduce (for bugs)
- create a failing check
- register a handler for it
- make the handler raise an exception

## Context
Missing these errors leads to missed alerts because events are not handled properly.

## Your Environment
* Sensu version used: 0.26.5
* Active Sensu extensions (e.g. WizardVan 0.1.0): sensu-handler-slack Plugin
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): Redis as transport

### PR DESCRIPTION
**Pull request by cwjohnston**
## Description

This change uses the exit status of a pipe handler to determine the level at which that handler's output should be logged. Handler output is logged at the `info` level when the exit status is 0, otherwise the output is logged at the `error` level.

## Related Issue

Closes #1542 

## Motivation and Context

Logging handler errors at `info` level can make it harder to discover handler errors in server logs.

## How Has This Been Tested?

Added spec for a handler exiting with a non-zero status.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/sensu/server/handle.rb [hunk 1]
```diff
@@ -26,16 +26,21 @@ def handler_error(handler, event_data)
...
       def pipe_handler(handler, event_data)
         options = {:data => event_data, :timeout => handler[:timeout]}
         Spawn.process(handler[:command], options) do |output, status|
-          @logger.info("handler output", {
-            :handler => handler,
-            :output => output.split("\n+")
-          })
+          log_level = status == 0 ? :info : :error
+          @logger.send(log_level, "handler output", {
+              :handler => handler,
```
Comment (portertech) [inline lib/sensu/server/handle.rb]: @cwjohnston looks great, but this should only be indented by 2 spaces.

Comment (cwjohnston) [inline lib/sensu/server/handle.rb]: @portertech indentation fixed 👍
